import { Cliente, Viagem, ProdutoViagem, Orcamento, PerfilConsultor, AlertItem, Reembolso, TipoProduto } from '../types';

export const MOCK_CONSULTORES: PerfilConsultor[] = [
  {
    id: 'sandbox-user-id',
    nome: 'Consultor Demonstrativo',
    email: 'consultor.fake@paxflowdemo.com',
    role: 'admin',
    ativo: true,
    avatar_url: 'lion',
    xp: 1500,
    nivel: 4
  },
  {
    id: 'sandbox-consultor-juliana',
    nome: 'Juliana Santos',
    email: 'juliana.fake@paxflowdemo.com',
    role: 'admin',
    ativo: true,
    avatar_url: 'panda',
    xp: 4500,
    nivel: 8
  },
  {
    id: 'sandbox-consultor-pedro',
    nome: 'Pedro Alencar',
    email: 'pedro.fake@paxflowdemo.com',
    role: 'consultor',
    ativo: true,
    avatar_url: 'fox',
    xp: 2200,
    nivel: 4
  },
  {
    id: 'sandbox-consultor-beatriz',
    nome: 'Beatriz Costa',
    email: 'beatriz.fake@paxflowdemo.com',
    role: 'consultor',
    ativo: true,
    avatar_url: 'koala',
    xp: 800,
    nivel: 2
  }
];

export const MOCK_CLIENTES: Cliente[] = [
  {
    id: 'sandbox-cliente-1',
    nome: 'João da Silva Fictício',
    email: 'joao.fake@paxflowdemo.com',
    telefone: '(11) 98888-8881',
    documento: '453.647.280-05', // CPF válido matemático
    dataNascimento: '1980-05-15',
    endereco: 'Rua das Simulações, 123 - Centro',
    observacoes: 'Passageiro frequente do modo demonstração.',
    consultorResponsavelId: 'sandbox-user-id',
    passaporteNumero: 'FP987654',
    passaporteValidade: '2026-08-10', // SLA urgente (< 180 dias do dia 23/06/2026)
    vistosInformacoes: 'Visto Americano B1/B2 ativo até 2030.',
    googleDriveFolderUrl: '/documento_demo.pdf', // Simulação do visualizador inline
    classificacoes: ['Premium', 'Frequente']
  },
  {
    id: 'sandbox-cliente-2',
    nome: 'Maria de Orlando Fake',
    email: 'maria.fake@paxflowdemo.com',
    telefone: '(11) 98888-8882',
    documento: '34.789.120/0001-31', // CNPJ válido matemático
    dataNascimento: '1975-10-20',
    endereco: 'Av. das Cotações, 500 - Orlando',
    observacoes: 'Cliente corporativo com alta recorrência.',
    consultorResponsavelId: 'sandbox-user-id',
    passaporteNumero: 'MP123456',
    passaporteValidade: '2032-01-15',
    vistosInformacoes: 'Isenta de visto europeu.',
    googleDriveFolderUrl: '/documento_demo.pdf',
    classificacoes: ['Corporativo']
  },
  {
    id: 'sandbox-cliente-3',
    nome: 'Carlos Simulado',
    email: 'carlos.fake@paxflowdemo.com',
    telefone: '(11) 98888-8883',
    documento: '864.293.750-56', // CPF válido matemático
    dataNascimento: '1992-12-01',
    endereco: 'Alameda Fictícia, 99',
    observacoes: 'Viagem de lua de mel simulada.',
    consultorResponsavelId: 'sandbox-user-id',
    passaporteNumero: 'CP456789',
    passaporteValidade: '2026-12-25', // SLA de aviso
    vistosInformacoes: 'Sem vistos cadastrados.',
    googleDriveFolderUrl: '/documento_demo.pdf',
    classificacoes: ['Lazer']
  },
  {
    id: 'sandbox-cliente-4',
    nome: 'Mariana Costa',
    email: 'mariana.costa@paxflowdemo.com',
    telefone: '(11) 99111-2233',
    documento: '111.222.333-44',
    dataNascimento: '1986-04-12',
    endereco: 'Av. Paulista, 1000 - São Paulo',
    observacoes: 'Cliente VIP com preferência por viagens em família e resorts em Orlando.',
    consultorResponsavelId: 'sandbox-user-id',
    passaporteNumero: 'MC987654',
    passaporteValidade: '2029-05-20',
    vistosInformacoes: 'Visto Americano B1/B2 válido até 2032.',
    googleDriveFolderUrl: '/documento_demo.pdf',
    classificacoes: ['VIP', 'Família', 'Promotor NPS']
  },
  {
    id: 'sandbox-cliente-5',
    nome: 'Carlos Eduardo Oliveira',
    email: 'carlos.eduardo@paxflowdemo.com',
    telefone: '(21) 98222-3344',
    documento: '222.333.444-55',
    dataNascimento: '1982-08-25',
    endereco: 'Rua das Palmeiras, 45 - Rio de Janeiro',
    observacoes: 'Viagens de casal com foco em resorts all-inclusive e praias paradisíacas.',
    consultorResponsavelId: 'sandbox-user-id',
    passaporteNumero: 'CE123456',
    passaporteValidade: '2030-11-10',
    vistosInformacoes: 'Isento de visto para o Caribe e México.',
    googleDriveFolderUrl: '/documento_demo.pdf',
    classificacoes: ['Lazer', 'Resort', 'Casal']
  },
  {
    id: 'sandbox-cliente-6',
    nome: 'Fernanda & Gabriel Santos',
    email: 'fernanda.santos@paxflowdemo.com',
    telefone: '(31) 99333-4455',
    documento: '333.444.555-66',
    dataNascimento: '1990-01-30',
    endereco: 'Av. Afonso Pena, 800 - Belo Horizonte',
    observacoes: 'Entusiastas de circuitos europeus e viagens culturais de longa duração.',
    consultorResponsavelId: 'sandbox-user-id',
    passaporteNumero: 'FS654321',
    passaporteValidade: '2028-09-15',
    vistosInformacoes: 'Isenta de visto no Espaço Schengen.',
    googleDriveFolderUrl: '/documento_demo.pdf',
    classificacoes: ['Europa', 'Promotor NPS']
  },
  {
    id: 'sandbox-cliente-7',
    nome: 'Roberto & Patricia Alcantara',
    email: 'roberto.alcantara@paxflowdemo.com',
    telefone: '(41) 99444-5566',
    documento: '444.555.666-77',
    dataNascimento: '1978-11-14',
    endereco: 'Rua das Flores, 200 - Curitiba',
    observacoes: 'Fãs de cruzeiros marítimos e viagens de luxo.',
    consultorResponsavelId: 'sandbox-user-id',
    passaporteNumero: 'RA789123',
    passaporteValidade: '2031-03-20',
    vistosInformacoes: 'Visto Americano e visto caribenho válidos.',
    googleDriveFolderUrl: '/documento_demo.pdf',
    classificacoes: ['Cruzeiros', 'Premium']
  },
  {
    id: 'sandbox-cliente-8',
    nome: 'Luciana Andrade',
    email: 'luciana.andrade@paxflowdemo.com',
    telefone: '(11) 97654-3210',
    documento: '555.666.777-88',
    dataNascimento: '1993-07-08',
    endereco: 'Alameda Santos, 500 - São Paulo',
    observacoes: 'Primeira viagem internacional solo para Paris. Requer atenção pré-embarque.',
    consultorResponsavelId: 'sandbox-user-id',
    passaporteNumero: '',
    passaporteValidade: '',
    vistosInformacoes: '',
    googleDriveFolderUrl: '/documento_demo.pdf',
    classificacoes: ['Internacional', 'Primeira Viagem']
  }
];

const __now = new Date();
const __curYear = __now.getFullYear();
const __curMonthStr = String(__now.getMonth() + 1).padStart(2, '0');

// Formata uma data para o dia informado no mês corrente: 'YYYY-MM-DD'
export const getCurMonthDate = (day: number): string => {
  const d = Math.min(Math.max(day, 1), 28);
  return `${__curYear}-${__curMonthStr}-${String(d).padStart(2, '0')}`;
};

// Formata uma data para o próximo mês
export const getNextMonthDate = (day: number): string => {
  const nm = new Date(__now.getFullYear(), __now.getMonth() + 1, 1);
  const y = nm.getFullYear();
  const m = String(nm.getMonth() + 1).padStart(2, '0');
  const d = Math.min(Math.max(day, 1), 28);
  return `${y}-${m}-${String(d).padStart(2, '0')}`;
};

// Formata uma data para meses anteriores (para histórico e NextTrip Engine > 9 meses)
export const getPastMonthsDate = (monthsAgo: number, day: number): string => {
  const pm = new Date(__now.getFullYear(), __now.getMonth() - monthsAgo, 1);
  const y = pm.getFullYear();
  const m = String(pm.getMonth() + 1).padStart(2, '0');
  const d = Math.min(Math.max(day, 1), 28);
  return `${y}-${m}-${String(d).padStart(2, '0')}`;
};

export const MOCK_VIAGENS: Viagem[] = [
  {
    id: 'sandbox-viagem-1',
    cliente_id: 'sandbox-cliente-1',
    clienteId: 'sandbox-cliente-1',
    consultor_id: 'sandbox-user-id',
    consultorId: 'sandbox-user-id',
    destino: 'Orlando & Parques Universal',
    data_ida: getCurMonthDate(15),
    dataIda: getCurMonthDate(15),
    data_volta: getCurMonthDate(25),
    dataVolta: getCurMonthDate(25),
    valor_total: 28500,
    valorTotal: 28500,
    status: 'pre_embarque',
    codigo_localizador: 'LOCFAK1',
    codigoLocalizador: 'LOCFAK1',
    origem: 'São Paulo (GRU)',
    data_financeiro: getCurMonthDate(2),
    dataFinanceiro: getCurMonthDate(2),
    observacoes: 'Verificar emissão do aéreo e ingressos dos parques.',
    createdAt: new Date().toISOString(),
    created_at: new Date().toISOString()
  },
  {
    id: 'sandbox-viagem-2',
    cliente_id: 'sandbox-cliente-2',
    clienteId: 'sandbox-cliente-2',
    consultor_id: 'sandbox-user-id',
    consultorId: 'sandbox-user-id',
    destino: 'Bariloche & Neve',
    data_ida: getCurMonthDate(1),
    dataIda: getCurMonthDate(1),
    data_volta: getCurMonthDate(10),
    dataVolta: getCurMonthDate(10),
    valor_total: 34200,
    valorTotal: 34200,
    status: 'pos_viagem',
    codigo_localizador: 'LOCFAK2',
    codigoLocalizador: 'LOCFAK2',
    origem: 'Rio de Janeiro (GIG)',
    data_financeiro: getCurMonthDate(1),
    dataFinanceiro: getCurMonthDate(1),
    observacoes: 'Viagem concluída com sucesso. Ligar para colher pesquisa NPS.',
    createdAt: new Date().toISOString(),
    created_at: new Date().toISOString()
  },
  {
    id: 'sandbox-viagem-3',
    cliente_id: 'sandbox-cliente-3',
    clienteId: 'sandbox-cliente-3',
    consultor_id: 'sandbox-user-id',
    consultorId: 'sandbox-user-id',
    destino: 'Mochilão Peru & Machu Picchu',
    data_ida: getCurMonthDate(18),
    dataIda: getCurMonthDate(18),
    data_volta: getCurMonthDate(27),
    dataVolta: getCurMonthDate(27),
    valor_total: 15800,
    valorTotal: 15800,
    status: 'planejamento',
    codigo_localizador: 'LOCFAK3',
    codigoLocalizador: 'LOCFAK3',
    origem: 'Brasília (BSB)',
    data_financeiro: getCurMonthDate(5),
    dataFinanceiro: getCurMonthDate(5),
    observacoes: 'Aguardando envio do contrato assinado pelo cliente.',
    createdAt: new Date().toISOString(),
    created_at: new Date().toISOString()
  },
  {
    id: 'sandbox-viagem-4',
    cliente_id: 'sandbox-cliente-1',
    clienteId: 'sandbox-cliente-1',
    consultor_id: 'sandbox-user-id',
    consultorId: 'sandbox-user-id',
    destino: 'Grécia & Ilhas Grega VIP',
    data_ida: getCurMonthDate(8),
    dataIda: getCurMonthDate(8),
    data_volta: getCurMonthDate(22),
    dataVolta: getCurMonthDate(22),
    valor_total: 42000,
    valorTotal: 42000,
    status: 'em_andamento',
    codigo_localizador: 'GREC2026',
    codigoLocalizador: 'GREC2026',
    origem: 'São Paulo (GRU)',
    data_financeiro: getCurMonthDate(3),
    dataFinanceiro: getCurMonthDate(3),
    observacoes: 'Passageiro em viagem no momento. Vouchers e traslado confirmados.',
    createdAt: new Date().toISOString(),
    created_at: new Date().toISOString()
  },
  {
    id: 'sandbox-viagem-5',
    cliente_id: 'sandbox-cliente-2',
    clienteId: 'sandbox-cliente-2',
    consultor_id: 'sandbox-user-id',
    consultorId: 'sandbox-user-id',
    destino: 'Santiago & Vinícolas',
    data_ida: getCurMonthDate(20),
    dataIda: getCurMonthDate(20),
    data_volta: getNextMonthDate(2),
    dataVolta: getNextMonthDate(2),
    valor_total: 19500,
    valorTotal: 19500,
    status: 'confirmada',
    codigo_localizador: 'STGO2026',
    codigoLocalizador: 'STGO2026',
    origem: 'Rio de Janeiro (GIG)',
    data_financeiro: getCurMonthDate(7),
    dataFinanceiro: getCurMonthDate(7),
    observacoes: 'Pacote confirmado. Enviar voucher do hotel no início da semana.',
    createdAt: new Date().toISOString(),
    created_at: new Date().toISOString()
  },
  // Oportunidades NextTrip Engine (Histórico de viagens concluídas há 10-12 meses)
  {
    id: 'sandbox-viagem-nexttrip-1',
    cliente_id: 'sandbox-cliente-4',
    clienteId: 'sandbox-cliente-4',
    consultor_id: 'sandbox-user-id',
    consultorId: 'sandbox-user-id',
    destino: 'Orlando / Disney (Pacote Família)',
    data_ida: getPastMonthsDate(11, 10),
    dataIda: getPastMonthsDate(11, 10),
    data_volta: getPastMonthsDate(11, 25),
    dataVolta: getPastMonthsDate(11, 25),
    valor_total: 38500,
    valorTotal: 38500,
    status: 'concluida',
    codigo_localizador: 'DISN2025',
    codigoLocalizador: 'DISN2025',
    origem: 'São Paulo (GRU)',
    data_financeiro: getPastMonthsDate(11, 20),
    dataFinanceiro: getPastMonthsDate(11, 20),
    nps_nota: 10,
    npsNota: 10,
    observacoes: 'Viagem incrível! Cliente pronta para reavaliar novas férias de família.',
    createdAt: getPastMonthsDate(11, 20) + 'T10:00:00Z',
    created_at: getPastMonthsDate(11, 20) + 'T10:00:00Z'
  },
  {
    id: 'sandbox-viagem-nexttrip-2',
    cliente_id: 'sandbox-cliente-5',
    clienteId: 'sandbox-cliente-5',
    consultor_id: 'sandbox-user-id',
    consultorId: 'sandbox-user-id',
    destino: 'Cancún - Resort All-Inclusive',
    data_ida: getPastMonthsDate(12, 1),
    dataIda: getPastMonthsDate(12, 1),
    data_volta: getPastMonthsDate(12, 12),
    dataVolta: getPastMonthsDate(12, 12),
    valor_total: 22400,
    valorTotal: 22400,
    status: 'concluida',
    codigo_localizador: 'CANC2025',
    codigoLocalizador: 'CANC2025',
    origem: 'Rio de Janeiro (GIG)',
    data_financeiro: getPastMonthsDate(12, 15),
    dataFinanceiro: getPastMonthsDate(12, 15),
    nps_nota: 9,
    npsNota: 9,
    observacoes: 'Adorou o resort all-inclusive. Querem nova oferta para o mesmo período.',
    createdAt: getPastMonthsDate(12, 15) + 'T14:30:00Z',
    created_at: getPastMonthsDate(12, 15) + 'T14:30:00Z'
  },
  {
    id: 'sandbox-viagem-nexttrip-3',
    cliente_id: 'sandbox-cliente-6',
    clienteId: 'sandbox-cliente-6',
    consultor_id: 'sandbox-user-id',
    consultorId: 'sandbox-user-id',
    destino: 'Europa (Paris, Roma e Madri)',
    data_ida: getPastMonthsDate(10, 5),
    dataIda: getPastMonthsDate(10, 5),
    data_volta: getPastMonthsDate(10, 20),
    dataVolta: getPastMonthsDate(10, 20),
    valor_total: 45000,
    valorTotal: 45000,
    status: 'concluida',
    codigo_localizador: 'EUR2025',
    codigoLocalizador: 'EUR2025',
    origem: 'Belo Horizonte (CNF)',
    data_financeiro: getPastMonthsDate(10, 15),
    dataFinanceiro: getPastMonthsDate(10, 15),
    nps_nota: 10,
    npsNota: 10,
    observacoes: 'Viagem inesquecível. Prometeram fazer uma nova rota europeia este ano.',
    createdAt: getPastMonthsDate(10, 15) + 'T11:00:00Z',
    created_at: getPastMonthsDate(10, 15) + 'T11:00:00Z'
  },
  {
    id: 'sandbox-viagem-nexttrip-4',
    cliente_id: 'sandbox-cliente-7',
    clienteId: 'sandbox-cliente-7',
    consultor_id: 'sandbox-user-id',
    consultorId: 'sandbox-user-id',
    destino: 'Cruzeiro Marítimo MSC pelo Caribe',
    data_ida: getPastMonthsDate(11, 10),
    dataIda: getPastMonthsDate(11, 10),
    data_volta: getPastMonthsDate(11, 20),
    dataVolta: getPastMonthsDate(11, 20),
    valor_total: 29800,
    valorTotal: 29800,
    status: 'concluida',
    codigo_localizador: 'CRUZ2025',
    codigoLocalizador: 'CRUZ2025',
    origem: 'São Paulo (GRU)',
    data_financeiro: getPastMonthsDate(11, 20),
    dataFinanceiro: getPastMonthsDate(11, 20),
    nps_nota: 9,
    npsNota: 9,
    observacoes: 'Excelente cruzeiro. Aguardando divulgação da nova temporada.',
    createdAt: getPastMonthsDate(11, 20) + 'T09:15:00Z',
    created_at: getPastMonthsDate(11, 20) + 'T09:15:00Z'
  },
  // Viagens ativas para o PaxFlow Risk Score™ (no mês corrente!)
  {
    id: 'sandbox-viagem-risk-1',
    cliente_id: 'sandbox-cliente-8',
    clienteId: 'sandbox-cliente-8',
    consultor_id: 'sandbox-user-id',
    consultorId: 'sandbox-user-id',
    destino: 'Paris, França',
    data_ida: getCurMonthDate(19),
    dataIda: getCurMonthDate(19),
    data_volta: getCurMonthDate(28),
    dataVolta: getCurMonthDate(28),
    valor_total: 22900,
    valorTotal: 22900,
    status: 'pre_embarque',
    codigo_localizador: 'PARIS26',
    codigoLocalizador: 'PARIS26',
    origem: 'São Paulo (GRU)',
    data_financeiro: getCurMonthDate(4),
    dataFinanceiro: getCurMonthDate(4),
    processo_conferido: false,
    isProcessoConferido: false,
    observacoes: 'Risco Ativo: Passageira internacional sem passaporte e sem seguro viagem.',
    createdAt: new Date().toISOString(),
    created_at: new Date().toISOString()
  },
  {
    id: 'sandbox-viagem-risk-2',
    cliente_id: 'sandbox-cliente-3',
    clienteId: 'sandbox-cliente-3',
    consultor_id: 'sandbox-user-id',
    consultorId: 'sandbox-user-id',
    destino: 'Orlando & Miami, EUA',
    data_ida: getCurMonthDate(21),
    dataIda: getCurMonthDate(21),
    data_volta: getNextMonthDate(5),
    dataVolta: getNextMonthDate(5),
    valor_total: 31200,
    valorTotal: 31200,
    status: 'planejamento',
    codigo_localizador: 'ORL2026',
    codigoLocalizador: 'ORL2026',
    origem: 'Brasília (BSB)',
    data_financeiro: getCurMonthDate(6),
    dataFinanceiro: getCurMonthDate(6),
    processo_conferido: false,
    isProcessoConferido: false,
    observacoes: 'Risco Médio: Conferência da equipe pendente e hotel sem voucher.',
    createdAt: new Date().toISOString(),
    created_at: new Date().toISOString()
  },
  {
    id: 'sandbox-viagem-risk-3',
    cliente_id: 'sandbox-cliente-2',
    clienteId: 'sandbox-cliente-2',
    consultor_id: 'sandbox-user-id',
    consultorId: 'sandbox-user-id',
    destino: 'Lisboa & Porto, Portugal',
    data_ida: getCurMonthDate(23),
    dataIda: getCurMonthDate(23),
    data_volta: getNextMonthDate(4),
    dataVolta: getNextMonthDate(4),
    valor_total: 31000,
    valorTotal: 31000,
    status: 'pre_embarque',
    codigo_localizador: 'LIS2026',
    codigoLocalizador: 'LIS2026',
    origem: 'São Paulo (GRU)',
    data_financeiro: getCurMonthDate(8),
    dataFinanceiro: getCurMonthDate(8),
    processo_conferido: true,
    isProcessoConferido: true,
    voucher_geral_anexado: true,
    voucher_geral_pacote: '/documento_demo.pdf',
    observacoes: 'Viagem 100% blindada e conformada.',
    createdAt: new Date().toISOString(),
    created_at: new Date().toISOString()
  }
];

export const MOCK_PRODUTOS: ProdutoViagem[] = [
  {
    id: 'sandbox-produto-1',
    viagemId: 'sandbox-viagem-1',
    tipo: 'AÉREO OPERADORA',
    fornecedor: 'Air Fake',
    descricao: 'Voo GRU - TNE (Terra do Nunca) Ida e Volta',
    codigoReserva: 'LOCAIR1',
    valorCusto: 0,
    valorVenda: 2500,
    status: 'emitido',
    dataServico: '2026-06-29',
    tarifa: 2000,
    taxa: 200,
    comissao: 300,
    markup: 0,
    rav: 0,
    dados_adicionais: { tarifa: 2000, taxa: 200, comissao: 300 }
  },
  {
    id: 'sandbox-produto-2',
    viagemId: 'sandbox-viagem-1',
    tipo: 'HOTEL',
    fornecedor: 'Neverland Palace',
    descricao: 'Suíte Premium 16 noites com Café da Manhã',
    codigoReserva: 'LOCHOT1',
    valorCusto: 0,
    valorVenda: 1000,
    status: 'reservado',
    dataServico: '2026-06-29',
    tarifa: 800,
    taxa: 100,
    comissao: 100,
    markup: 0,
    rav: 0,
    dados_adicionais: { tarifa: 800, taxa: 100, comissao: 100 }
  },
  {
    id: 'sandbox-produto-3',
    viagemId: 'sandbox-viagem-2',
    tipo: 'Circuito',
    fornecedor: 'Mundo Perdido Tours',
    descricao: 'Circuito de Aventura pelas Cidades de Ouro 14 dias',
    codigoReserva: 'LOCCIR1',
    valorCusto: 0,
    valorVenda: 8200,
    status: 'emitido',
    dataServico: '2026-06-01',
    tarifa: 7000,
    taxa: 500,
    comissao: 700,
    markup: 0,
    rav: 0,
    dados_adicionais: { tarifa: 7000, taxa: 500, comissao: 700 }
  },
  {
    id: 'sandbox-produto-risk-1-aereo',
    viagemId: 'sandbox-viagem-risk-1',
    tipo: 'AÉREO OPERADORA',
    fornecedor: 'Air France',
    descricao: 'Voo GRU - CDG Ida e Volta',
    codigoReserva: 'PARIS26',
    valorCusto: 5000,
    valorVenda: 6500,
    status: 'emitido',
    dataServico: '2026-09-15',
    tarifa: 5500,
    taxa: 500,
    comissao: 500,
    markup: 0,
    rav: 0,
    dados_adicionais: { tarifa: 5500, taxa: 500, comissao: 500 }
  },
  {
    id: 'sandbox-produto-risk-2-hotel',
    viagemId: 'sandbox-viagem-risk-2',
    tipo: 'HOTEL',
    fornecedor: 'Universal Endless Summer',
    descricao: 'Suíte Standard 14 noites',
    codigoReserva: '',
    valorCusto: 8000,
    valorVenda: 10500,
    status: 'reservado',
    dataServico: '2026-09-20',
    tarifa: 9000,
    taxa: 500,
    comissao: 1000,
    markup: 0,
    rav: 0,
    dados_adicionais: {}
  },
  {
    id: 'sandbox-produto-risk-3-aereo',
    viagemId: 'sandbox-viagem-risk-3',
    tipo: 'AÉREO OPERADORA',
    fornecedor: 'TAP Air Portugal',
    descricao: 'Voo GRU - LIS Ida e Volta',
    codigoReserva: 'LIS2026',
    valorCusto: 4800,
    valorVenda: 6200,
    status: 'emitido',
    dataServico: '2026-09-10',
    tarifa: 5200,
    taxa: 500,
    comissao: 500,
    markup: 0,
    rav: 0,
    dados_adicionais: { tarifa: 5200, taxa: 500, comissao: 500 }
  },
  {
    id: 'sandbox-produto-risk-3-hotel',
    viagemId: 'sandbox-viagem-risk-3',
    tipo: 'HOTEL',
    fornecedor: 'Dom Pedro Lisboa',
    descricao: 'Quarto Deluxe 12 noites',
    codigoReserva: 'HOSP2026',
    valorCusto: 6000,
    valorVenda: 8000,
    status: 'emitido',
    dataServico: '2026-09-10',
    tarifa: 7000,
    taxa: 400,
    comissao: 600,
    markup: 0,
    rav: 0,
    dados_adicionais: { voucher_url: '/documento_demo.pdf' }
  },
  {
    id: 'sandbox-produto-risk-3-seguro',
    viagemId: 'sandbox-viagem-risk-3',
    tipo: 'SEGURO VIAGEM',
    fornecedor: 'Assist Card',
    descricao: 'Cobertura 150k EUR Europa',
    codigoReserva: 'SEG2026',
    valorCusto: 800,
    valorVenda: 1200,
    status: 'emitido',
    dataServico: '2026-09-10',
    tarifa: 1000,
    taxa: 50,
    comissao: 150,
    markup: 0,
    rav: 0,
    dados_adicionais: {}
  }
];

export const MOCK_ORCAMENTOS: Orcamento[] = [
  {
    id: 'sandbox-orcamento-1',
    consultorId: 'sandbox-user-id',
    nomeCliente: 'Paula Cotação Fake',
    contato: '(11) 97777-1111 / paula.fake@paxflowdemo.com',
    destino: 'Ilha da Fantasia',
    dataViagem: '2026-09-12',
    temperatura: 'Quente',
    tags: ['Família', 'Resort'],
    status: 'SOLICITADO',
    valorProposta: 6400,
    origem: 'Instagram',
    notasNegociacao: 'Cliente super interessada no pacote de 7 dias com tudo incluso.',
    documentosUrl: ['/documento_demo.pdf'],
    createdAt: new Date().toISOString()
  },
  {
    id: 'sandbox-orcamento-2',
    consultorId: 'sandbox-user-id',
    nomeCliente: 'Lucas Interesse Fake',
    contato: '(21) 98888-2222 / lucas.fake@paxflowdemo.com',
    destino: 'Asgard (Mitologia)',
    dataViagem: '2026-11-20',
    temperatura: 'Frio',
    tags: ['Aventura', 'Exótico'],
    status: 'EM_ANDAMENTO',
    valorProposta: 15000,
    origem: 'Indicação',
    notasNegociacao: 'Orçamento complexo com passeios temáticos de mitologia nórdica.',
    documentosUrl: [],
    createdAt: new Date().toISOString()
  },
  {
    id: 'sandbox-orcamento-3',
    consultorId: 'sandbox-user-id',
    nomeCliente: 'Guilherme Negociação',
    contato: '(31) 99999-3333 / guilherme@paxflowdemo.com',
    destino: 'Machu Picchu, Peru',
    dataViagem: '2026-10-05',
    temperatura: 'Normal',
    tags: ['Cultura', 'Trilha'],
    status: 'AGUARDANDO',
    valorProposta: 8900,
    origem: 'Google',
    notasNegociacao: 'Voo reservado. Aguardando feedback do cliente sobre o hotel em Cusco.',
    documentosUrl: ['/documento_demo.pdf'],
    createdAt: new Date().toISOString()
  },
  {
    id: 'sandbox-orcamento-4',
    consultorId: 'sandbox-user-id',
    nomeCliente: 'Natália Ganha',
    contato: '(11) 98888-4444 / natalia@paxflowdemo.com',
    destino: 'Paris, França',
    dataViagem: '2026-12-25',
    temperatura: 'Quente',
    tags: ['Europa', 'Lua de Mel'],
    status: 'CONCLUIDO',
    subStatus: 'ACEITO',
    valorProposta: 23700,
    valorViagem: 23700,
    origem: 'Instagram',
    notasNegociacao: 'Venda fechada com sucesso! Upgrade de quarto incluso.',
    documentosUrl: ['/documento_demo.pdf'],
    createdAt: new Date().toISOString()
  },
  {
    id: 'sandbox-orcamento-5',
    consultorId: 'sandbox-user-id',
    nomeCliente: 'Roberto Desistente',
    contato: '(21) 98888-5555',
    destino: 'Buenos Aires, Argentina',
    dataViagem: '2026-08-20',
    temperatura: 'Frio',
    tags: ['América do Sul', 'Show'],
    status: 'CONCLUIDO',
    subStatus: 'DESISTENCIA',
    valorProposta: 4500,
    origem: 'Google',
    notasNegociacao: 'Desistiu devido a alteração de data das férias no trabalho.',
    documentosUrl: [],
    createdAt: new Date().toISOString()
  }
];

export const MOCK_REEMBOLSOS: Reembolso[] = [
  {
    id: 'sandbox-reembolso-1',
    viagemId: 'sandbox-viagem-1',
    viagem_id: 'sandbox-viagem-1',
    produtoViagemId: 'sandbox-produto-2',
    produto_viagem_id: 'sandbox-produto-2',
    consultorSolicitanteId: 'sandbox-user-id',
    consultor_solicitante_id: 'sandbox-user-id',
    valorSolicitado: 1000,
    valor_solicitado: 1000,
    valorAprovado: 900,
    valor_aprovado: 900,
    taxaRetencao: 100,
    taxa_retencao: 100,
    status: 'em_analise',
    observacoesFinanceiras: 'Aguardando confirmação de cancelamento pela Neverland Palace.',
    dataSolicitacao: '2026-06-20',
    data_solicitacao: '2026-06-20',
    createdAt: new Date().toISOString(),
    created_at: new Date().toISOString()
  }
];

export const MOCK_TIPOS_PRODUTO: TipoProduto[] = [
  {
    id: 'tipo-hotel',
    nome: 'HOTEL',
    icone: 'hotel',
    ativo: true,
    campos_adicionais: [
      {
        id: 'hotel-regime',
        label: 'Regime de Alimentação',
        tipo: 'select',
        opcoes: ['Café da Manhã', 'Meia Pensão', 'Pensão Completa', 'All Inclusive'],
        obrigatorio: true,
        alvo: 'dados_adicionais'
      }
    ],
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z'
  },
  {
    id: 'tipo-aereo',
    nome: 'AÉREO OPERADORA',
    icone: 'flight',
    ativo: true,
    campos_adicionais: [
      {
        id: 'aereo-franquia',
        label: 'Franquia de Bagagem',
        tipo: 'select',
        opcoes: ['Sem Bagagem', '1x 23kg Inclusa', '2x 23kg Inclusas'],
        obrigatorio: true,
        alvo: 'dados_adicionais'
      }
    ],
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z'
  }
];

export const MOCK_ALERTS: AlertItem[] = [
  {
    id: 'sandbox-alert-1',
    type: 'passport',
    title: '⚠️ SLA Passaporte Expirando',
    sender: 'Sistema PaxFlow',
    senderAvatar: 'koala',
    dateStr: 'Hoje',
    subject: 'SLA urgente de validade do passaporte do passageiro João da Silva Fictício',
    body: 'O passaporte do passageiro principal João da Silva Fictício expira em 10/08/2026 (menos de 180 dias do embarque para Terra do Nunca). Favor alertar o cliente sobre a urgência de renovação.',
    targetId: 'sandbox-cliente-1',
    arquivado: false,
    consultorId: 'sandbox-user-id',
    consultorNome: 'Consultor Demonstrativo',
    createdAt: new Date().toISOString(),
    eventDate: '2026-08-10'
  },
  {
    id: 'sandbox-alert-2',
    type: 'direct_message',
    title: 'Juliana Santos',
    sender: 'Juliana Santos',
    senderAvatar: 'panda',
    dateStr: 'Ontem',
    subject: 'Revisão de Rentabilidade do Pós-Venda',
    body: 'Olá! Estava revisando as rentabilidades das viagens fechadas esta semana e notei que a comissão da viagem de El Dorado da Maria ficou excelente! Ótimo trabalho trazendo o circuito da Mundo Perdido Tours.',
    targetId: 'sandbox-viagem-2',
    arquivado: false,
    consultorId: 'sandbox-user-id',
    consultorNome: 'Consultor Demonstrativo',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    eventDate: new Date().toISOString().split('T')[0],
    isSent: false,
    senderId: 'sandbox-consultor-juliana'
  }
];
